[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
monitor_speed = 115200
lib_ldf_mode = deep
lib_deps =
  m5stack/M5Unified@^0.2.5
  https://github.com/stack-chan/stackchan-arduino.git
