[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  ; gob_GC0308 の依存ライブラリが古いAPIを使っているため抑制（C++向け）
  -Wno-deprecated-declarations
extra_scripts = fix_c_warnings.py
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified@^0.2.5
  https://github.com/GOB52/gob_GC0308.git@^0.1.0
